#!/bin/bash
# Google Sheets读取示例脚本

echo "=========================================="
echo "Google Sheets 数据读取示例"
echo "=========================================="
echo ""
echo "使用方法："
echo ""
echo "1. 基本读取（通过Sheet ID）："
echo "   python3 scripts/read_gsheets.py '1ABC...XYZ'"
echo ""
echo "2. 通过完整URL读取："
echo "   python3 scripts/read_gsheets.py 'https://docs.google.com/spreadsheets/d/1ABC...XYZ/edit'"
echo ""
echo "3. 读取指定工作表（第2个）："
echo "   python3 scripts/read_gsheets.py 'SHEET_ID' -w 1"
echo ""
echo "4. 读取指定范围："
echo "   python3 scripts/read_gsheets.py 'SHEET_ID' -r 'A1:D10'"
echo ""
echo "5. 保存到文件："
echo "   python3 scripts/read_gsheets.py 'SHEET_ID' -o output/data.json"
echo ""
echo "6. 使用自定义凭证文件："
echo "   python3 scripts/read_gsheets.py 'SHEET_ID' -c /path/to/credentials.json"
echo ""
echo "=========================================="
echo "注意事项："
echo "=========================================="
echo ""
echo "1. 需要先配置 credentials.json 文件"
echo "2. 需要在Google Sheets中共享表格给服务账号"
echo "3. 服务账号邮箱格式: xxx@xxx.iam.gserviceaccount.com"
echo ""
echo "详细配置步骤请查看: Documents/GOOGLE_SHEETS.md"
echo ""
